config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :users
  resources :startups
  root 'pages#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/startup.rb
class Startup < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:headline, :city, :email, :about, :skills, :sectors)
    end
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :set_startup, only: [:show, :edit, :update, :destroy]

  # GET /startups
  # GET /startups.json
  def index
    @startups = Startup.all
  end

  # GET /startups/1
  # GET /startups/1.json
  def show
  end

  # GET /startups/new
  def new
    @startup = Startup.new
  end

  # GET /startups/1/edit
  def edit
  end

  # POST /startups
  # POST /startups.json
  def create
    @startup = Startup.new(startup_params)

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup, notice: 'Startup was successfully created.' }
        format.json { render :show, status: :created, location: @startup }
      else
        format.html { render :new }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /startups/1
  # PATCH/PUT /startups/1.json
  def update
    respond_to do |format|
      if @startup.update(startup_params)
        format.html { redirect_to @startup, notice: 'Startup was successfully updated.' }
        format.json { render :show, status: :ok, location: @startup }
      else
        format.html { render :edit }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /startups/1
  # DELETE /startups/1.json
  def destroy
    @startup.destroy
    respond_to do |format|
      format.html { redirect_to startups_url, notice: 'Startup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_startup
      @startup = Startup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def startup_params
      params.require(:startup).permit(:headline, :city, :email, :about, :skills, :sectors)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :city, :about)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <title>Matchr</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%#= csrf_meta_tags %>
</head>



<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
  <div class="col-md-9">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Matchr</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>-->
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
      <ul class="navbar-form navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, :class => " btn btn-default" %>
          <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-default" %>
        <% end %>
        <!--<li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>-->
      </ul>
    </div><!-- /.navbar-collapse --></div><!--colspan-->
  </div><!-- /.container-fluid -->
</nav>
<body>
 <!--Ensure you have flash messages in app/views/layouts/application.html.erb. For example:-->
 <p><%= notice %></p>
 <p><%= alert %></p>
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/pages/index.html.erb
<div class="col-lg-9">

	<h1>Welcome to Matchr</h1>
	<hr>

	<p>Matcher is a free service that helps you team up for tech projects and startups near you.</p>

	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h2 class="panel-title">Post</h2>
	  </div>
	  <div class="panel-body">
		  <p>Help others find you by creating a profile for yourself, a tech project, and/or your startup.</p>
		  <p><a href="/users/new"><i class="fa fa-user-plus"></i><strong>&nbsp;User</strong></a>&nbsp;&nbsp;&nbsp;&nbsp;</p>

		  <p><a href="/projects/new"><i class="fa fa-book"></i><strong>&nbsp;&nbsp;Project</strong></a></p>

		  <p><a href="/startups/new"><i class="fa fa-power-off"></i><strong>&nbsp;&nbsp;Startup</strong></a></p>
	  </div>
	</div>
	
<!--
	<div class="btn-group"> <!-- If non-mobile screen, allow hovering!>
		<button type="button" class="btn btn-lg btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
 			 Select a Profile Category<span class="caret"></span>
		</button>
	  <ul class="dropdown-menu" role="menu">
	    <li><a href="#"><i class="fa fa-user-plus"></i><strong>&nbsp;User</strong> - I'm available to join a project, activity, or startup</a></li>
	    <li><a href="#"><i class="fa fa-book"></i><strong>&nbsp;&nbsp;Project</strong> - I'd like someone to join my not-for profit (or TBD) activity/project</a></li>
	    <li><a href="#"><i class="fa fa-power-off"></i><strong>&nbsp;&nbsp;Startup</strong> - I'd like someone to join my for-profit activity/startup</a></li>
	  </ul>
	</div>
	
	<!--Submit a post
	Contact
	-->

	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h2 class="panel-title">View</h2>
	  </div>
	  <div class="panel-body">
		  <p>To view previously submitted profiles, please choose an option below:</p>
	
			<p><a href="/users"><i class="fa fa-user-plus"></i><strong>&nbsp;Users</strong></a></p>

		  <p><a href="/projects"><i class="fa fa-book"></i><strong>&nbsp;&nbsp;Projects</strong></a></p>

		  <p><a href="/startups"><i class="fa fa-power-off"></i><strong>&nbsp;&nbsp;Startups</strong></a></p>
	  </div>
	</div>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4">
    <form>
      <div class="form-group">
        <%= f.label 'Headline' %>
        <%= f.text_field :headline, class: 'form-control' %>
        <br>

        <%= f.label 'City' %>
        <%= f.text_field :city, class: 'form-control' %>
        <br>

        <%= f.label 'Email' %>
        <%= f.text_field :email, class: 'form-control' %>
        <br>

        <%= f.label 'About' %>
        <%= f.text_area :about, rows: 4, class: 'form-control' %>

        <br>
        <%= f.submit 'Submit', :class => 'btn btn-primary' %>
      </div>
    </form>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>All Projects</h1>
<hr>

<table class="table">
  <thead>
    <tr>
      <th>About</th>
      <th>Location</th>
      <th>Keywords</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.headline %></td>
        <td><%= project.city %></td>
        <td><%= project.skills %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!--<%#= link_to 'Show', project %></td>
        <td><%#= link_to 'Edit', edit_project_path(project) %></td>
        <td><%#= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->

<br>

<%= link_to 'New project', new_project_path %>

<!--<table>
  <thead>
    <tr>
      <th colspan="3"></th>
      <td><%#= project.headline %></td>
        <td><%#= project.city %></td>
        <td><%#= project.skills %></td>
    </tr>
  </thead>

  <tbody>
    <#% @projects.each do |project| %>
      <tr>
        <td><%#= link_to 'Show', project %></td>
        <td><%#= link_to 'Edit', edit_project_path(project) %></td>
        <td><%#= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Project', new_project_path %>-->

app/views/projects/new.html.erb
<h1>New Project</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1><%= @project.headline %></h1>
<hr>

<p><%= @project.city %></p>

<div class="col-lg-8">
  <div class="panel panel-default">
    <div class="panel-heading">
	    <strong>About</strong>
	  </div>
	  <div class="panel-body">
	    <%= @project.about %>
	  </div>
	</div>
</div>

<p>
	<%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', projects_path %>
</p>

</div>

app/views/startups/_form.html.erb
<%= form_for(@startup) do |f| %>
  <% if @startup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@startup.errors.count, "error") %> prohibited this startup from being saved:</h2>

      <ul>
      <% @startup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4">
    <form>
      <div class="form-group">
        <%= f.label 'Headline' %>
        <%= f.text_field :headline, class: 'form-control' %>
        <br>

        <%= f.label 'City' %>
        <%= f.text_field :city, class: 'form-control' %>
        <br>

        <%= f.label 'Email' %>
        <%= f.text_field :email, class: 'form-control' %>
        <br>

        <%= f.label 'About' %>
        <%= f.text_area :about, rows: 4, class: 'form-control' %>

        <br>
        <%= f.submit 'Submit', :class => 'btn btn-primary' %>
      </div>
    </form>
  </div>
<% end %>

app/views/startups/edit.html.erb
<h1>Edit Startup Pitch</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Cancel', @startup %> |
<%= link_to 'All Startups', startups_path %>

app/views/startups/index.html.erb
<h1>All Startups</h1>
<hr>

<table class="table">
  <thead>
    <tr>
      <th>About</th>
      <th>Location</th>
      <th>Keywords</th>
    </tr>
  </thead>

  <tbody>
    <% @startups.each do |startup| %>
      <tr>
        <td><%= startup.headline %></td>
        <td><%= startup.city %></td>
        <td><%= startup.skills %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!--<%#= link_to 'Show', startup %></td>
        <td><%#= link_to 'Edit', edit_startup_path(startup) %></td>
        <td><%#= link_to 'Destroy', startup, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->

<br>

<%= link_to 'New Startup', new_startup_path %>

<!--<table>
  <thead>
    <tr>
      <th colspan="3"></th>
      <td><%#= startup.headline %></td>
        <td><%#= startup.city %></td>
        <td><%#= startup.skills %></td>
    </tr>
  </thead>

  <tbody>
    <#% @startups.each do |startup| %>
      <tr>
        <td><%#= link_to 'Show', startup %></td>
        <td><%#= link_to 'Edit', edit_startup_path(startup) %></td>
        <td><%#= link_to 'Destroy', startup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Startup', new_startup_path %>-->

app/views/startups/new.html.erb
<h1>New Startup Profile</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Back', startups_path %>

app/views/startups/show.html.erb
<h1><%= @startup.headline %></h1>
<hr>

<p><%= @startup.city %></p>

<div class="col-lg-8">
  <div class="panel panel-default">
    <div class="panel-heading">
	    <strong>About</strong>
	  </div>
	  <div class="panel-body">
	    <%= @startup.about %>
	  </div>
	</div>
</div>

<p>
	<%= link_to 'Edit', edit_startup_path(@startup) %> |
  <%= link_to 'All Startups', startups_path %>
</p>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4">
    <form>
      <div class="form-group">
        <%= f.label 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>


        <%= f.label 'City' %>
        <%= f.text_field :city, class: 'form-control' %>
        <br>

        <%= f.label 'About Me' %>
        <%= f.text_area :about, rows: 4, class: 'form-control' %>

        <br>
        <%= f.submit 'Submit', :class => 'btn btn-primary' %>
      </div>
    </form>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<hr>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>About</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.city %></td>
        <td><%= user.about %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!--<%#= link_to 'Show', user %></td>
        <td><%#= link_to 'Edit', edit_user_path(user) %></td>
        <td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
	<h1>New User</h1>
	<hr>

	<%= render 'form' %>

app/views/users/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1><%= @user.name %></h1>
<hr>

<p><%= @user.city %></p>

<div class="col-lg-8">
  <div class="panel panel-default">
    <div class="panel-heading">
	    <strong>About</strong>
	  </div>
	  <div class="panel-body">
	    <%= @user.about %>
	  </div>
	</div>
</div>

<p>
	<%= link_to 'Edit', edit_user_path(@user) %> |
	<%= link_to 'Back to Main', "/" %>
</p>

</div>